### ISSUE TITLE
Tutorial doesn't create index.vue, only present in repo

### ISSUE THREAD

**Issue by rscorer** [supabase-community/nuxt3-quickstarter#5]
Tutorial doesn't create index.vue, only present in repo

**Comment by dshukertjr** [comment]
Thanks for opening this issue! 

Would you like to add it by yourself? You can add it to [this file](https://github.com/supabase/supabase/edit/master/web/docs/guides/with-nuxt-3.mdx) and submit a pull request! If you are busy, and would prefer not to, then that is okay too. I will add it when I have some time!

**Comment by thorwebdev** [comment]
Looks like this got merged in 🙌  Thanks so much @rscorer!
